import type { Agency, Regulation, Importance, Status } from "./types";
export const DEMO_DATE = "2026-09-09";
export const agencies: Agency[] = ["FDA", "EMA", "NMPA", "CDE", "ICH"];
export const topics = [
  "CMC / Quality",
  "Analytical",
  "Viral / Biological Safety",
  "Nonclinical",
  "Clinical",
  "Regulatory Submission",
  "Post-Approval",
];
export const products = [
  "Monoclonal Antibody",
  "Bispecific Antibody",
  "Multispecific Antibody",
  "ADC",
  "Fusion Protein",
  "Recombinant Protein",
  "Enzyme",
  "Cytokine",
  "Biosimilar",
  "Vaccine",
  "Cell Therapy",
  "Gene Therapy",
  "CAR-T",
  "mRNA",
  "Oligonucleotide",
  "Plasma Derived Product",
  "General Biologics",
];
export const stages = [
  "Discovery",
  "Preclinical",
  "IND Enabling",
  "IND / CTA",
  "Phase I",
  "Phase II",
  "Phase III",
  "BLA / MAA",
  "Commercial",
  "Post Approval",
];
export const departments = [
  "CMC",
  "Upstream",
  "Downstream",
  "Purification",
  "Formulation",
  "Analytical",
  "QC",
  "QA",
  "Manufacturing",
  "Clinical",
  "Nonclinical",
  "Regulatory Affairs",
  "Pharmacovigilance",
  "Project Management",
];
export const documentTypes = [
  "Final Guidance",
  "Draft Guidance",
  "Guideline",
  "Revised Guideline",
  "Q&A",
  "Reflection Paper",
  "Concept Paper",
  "Position Paper",
  "Recommendation",
  "Technical Guideline",
  "Notice",
  "Announcement",
  "Regulation",
  "Regulation Amendment",
  "征求意见稿",
  "指导原则",
  "技术指导原则",
  "公告",
  "通知",
];
export const statuses: Status[] = [
  "Draft",
  "Final",
  "Effective",
  "Revised",
  "Superseded",
  "Withdrawn",
  "Under Consultation",
  "Archived",
  "Unknown",
];
const samples: [Agency, string, string, string, string, Status, Importance][] =
  [
    [
      "FDA",
      "Manufacturing changes and comparability for therapeutic proteins",
      "治疗性蛋白生产变更与可比性研究",
      "CMC / Quality",
      "Final Guidance",
      "Final",
      "Critical",
    ],
    [
      "EMA",
      "Clinical development of biosimilar medicinal products",
      "生物类似药临床开发指南",
      "Clinical",
      "Revised Guideline",
      "Revised",
      "High",
    ],
    [
      "CDE",
      "Technical considerations for antibody–drug conjugate development",
      "抗体偶联药物药学研究技术考虑",
      "CMC / Quality",
      "征求意见稿",
      "Under Consultation",
      "High",
    ],
    [
      "ICH",
      "Viral safety evaluation of biotechnology products",
      "生物技术产品病毒安全性评价",
      "Viral / Biological Safety",
      "Guideline",
      "Final",
      "High",
    ],
    [
      "NMPA",
      "Registration documentation for biological products",
      "生物制品注册申报资料要求",
      "Regulatory Submission",
      "公告",
      "Effective",
      "High",
    ],
    [
      "FDA",
      "Potency assurance for cell therapy products",
      "细胞治疗产品效力保障",
      "Analytical",
      "Draft Guidance",
      "Draft",
      "High",
    ],
    [
      "EMA",
      "Post-authorisation changes for biological medicines",
      "生物药上市后变更管理",
      "Post-Approval",
      "Q&A",
      "Revised",
      "Medium",
    ],
    [
      "CDE",
      "Nonclinical safety evaluation of bispecific antibodies",
      "双特异性抗体非临床安全性评价",
      "Nonclinical",
      "技术指导原则",
      "Final",
      "High",
    ],
    [
      "ICH",
      "Analytical procedure development and validation",
      "分析方法开发与验证",
      "Analytical",
      "Guideline",
      "Final",
      "Medium",
    ],
    [
      "NMPA",
      "Pharmacovigilance reporting for biological products",
      "生物制品药物警戒报告管理",
      "Post-Approval",
      "通知",
      "Effective",
      "Medium",
    ],
    [
      "FDA",
      "Early phase clinical trials for gene therapies",
      "基因治疗早期临床试验",
      "Clinical",
      "Draft Guidance",
      "Draft",
      "High",
    ],
    [
      "EMA",
      "Cell substrates and cell bank characterisation",
      "细胞基质与细胞库表征",
      "CMC / Quality",
      "Reflection Paper",
      "Draft",
      "Medium",
    ],
    [
      "CDE",
      "Immunogenicity assessment of therapeutic proteins",
      "治疗性蛋白免疫原性评价",
      "Clinical",
      "指导原则",
      "Final",
      "High",
    ],
    [
      "ICH",
      "Lifecycle management of pharmaceutical products",
      "药品全生命周期管理",
      "Post-Approval",
      "Q&A",
      "Final",
      "Low",
    ],
    [
      "NMPA",
      "Electronic submission of biologics dossiers",
      "生物制品电子申报资料管理",
      "Regulatory Submission",
      "通知",
      "Effective",
      "Low",
    ],
  ];
export const regulations: Regulation[] = samples.map(
  (
    [
      regulator,
      title,
      title_zh,
      category,
      document_type,
      status,
      importance_level,
    ],
    i,
  ) => {
    const id = `mock-${i + 1}`;
    const date = i < 8 ? DEMO_DATE : `2026-09-0${8 - (i % 4)}`;
    const updated = [0, 1, 3, 6].includes(i);
    const text = `Development / Mock Data. Fictional demonstration of ${title.toLowerCase()}. This text is not a regulatory requirement and must not be cited as official guidance.`;
    const previous = updated ? `${id}-v1` : null;
    return {
      id,
      regulator,
      country_or_region: {
        FDA: "United States",
        EMA: "European Union",
        NMPA: "China",
        CDE: "China",
        ICH: "International",
        PMDA: "Japan",
      }[regulator],
      title_original: title,
      title_zh,
      document_number: `DEMO-${regulator}-${String(i + 1).padStart(3, "0")}`,
      document_type,
      status,
      publication_date: date,
      effective_date: null,
      updated_date: date,
      official_url: null,
      pdf_url: null,
      source_page_url: null,
      official_summary: null,
      summary_zh: `模拟内容：用于展示${title_zh}相关法规的阅读、分类与版本追踪体验，不构成监管要求。`,
      content_text: text,
      categories: [category],
      subcategories: [
        [
          "Comparability",
          "Biosimilar",
          "Process Development",
          "Viral Safety",
          "eCTD",
          "Potency",
          "Variation",
        ][i % 7],
      ],
      keywords: [category, title_zh],
      product_types: [
        [
          "Monoclonal Antibody",
          "Biosimilar",
          "ADC",
          "General Biologics",
          "Recombinant Protein",
          "Cell Therapy",
          "Gene Therapy",
        ][i % 7],
      ],
      development_stages: [stages[(i + 3) % stages.length]],
      affected_departments: [
        departments[i % departments.length],
        "Regulatory Affairs",
      ],
      importance_level,
      version: updated ? "2.0" : "1.0",
      previous_version_id: previous,
      is_current_version: true,
      is_new: !updated,
      is_updated: updated,
      content_hash: `mock-content-${i}`,
      source_hash: `mock-source-${i}`,
      first_detected_at: updated
        ? "2026-09-01T08:00:00+08:00"
        : `${date}T08:00:00+08:00`,
      last_checked_at: `${DEMO_DATE}T08:30:00+08:00`,
      created_at: `${date}T08:00:00+08:00`,
      updated_at: `${date}T08:30:00+08:00`,
      is_mock: true,
      versions: [
        ...(updated
          ? [
              {
                id: previous!,
                regulation_id: id,
                version_name: "1.0",
                document_url: null,
                pdf_url: null,
                publication_date: "2026-09-01",
                detected_at: "2026-09-01T08:00:00+08:00",
                status: "Draft" as Status,
                content_hash: `mock-old-${i}`,
                content_snapshot:
                  "Development / Mock Data. Previous illustrative draft.",
                previous_version_id: null,
                change_detected: "New",
              },
            ]
          : []),
        {
          id: `${id}-v${updated ? 2 : 1}`,
          regulation_id: id,
          version_name: updated ? "2.0" : "1.0",
          document_url: null,
          pdf_url: null,
          publication_date: date,
          detected_at: `${date}T08:30:00+08:00`,
          status,
          content_hash: `mock-content-${i}`,
          content_snapshot: text,
          previous_version_id: previous,
          change_detected: updated
            ? status === "Final"
              ? "Draft → Final"
              : "Content Changed"
            : "New",
        },
      ],
    };
  },
);
