ALTER TABLE watchlists ADD COLUMN country_or_regions TEXT[] NOT NULL DEFAULT '{}', ADD COLUMN affected_departments TEXT[] NOT NULL DEFAULT '{}', ADD COLUMN statuses "RegulationStatus"[] NOT NULL DEFAULT '{}', ADD COLUMN change_types TEXT[] NOT NULL DEFAULT '{}', ADD COLUMN minimum_severity "Importance";
CREATE TABLE watchlist_matches (id TEXT PRIMARY KEY, watchlist_id TEXT NOT NULL REFERENCES watchlists(id) ON DELETE CASCADE, regulation_id TEXT NOT NULL REFERENCES regulations(id) ON DELETE RESTRICT, change_event_id TEXT REFERENCES change_events(id) ON DELETE RESTRICT, matched_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, detected_at TIMESTAMPTZ(3) NOT NULL, match_type TEXT NOT NULL, reasons JSONB NOT NULL, dedupe_key TEXT NOT NULL UNIQUE);
CREATE INDEX watchlist_matches_watchlist_id_detected_at_idx ON watchlist_matches(watchlist_id,detected_at);
CREATE TABLE notification_events (id TEXT PRIMARY KEY, created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, regulation_id TEXT REFERENCES regulations(id) ON DELETE RESTRICT, change_event_id TEXT REFERENCES change_events(id) ON DELETE RESTRICT, watchlist_id TEXT REFERENCES watchlists(id) ON DELETE SET NULL, notification_type TEXT NOT NULL, title TEXT NOT NULL, message TEXT NOT NULL, regulator TEXT, change_types TEXT[] NOT NULL DEFAULT '{}', severity "Importance" NOT NULL, channel TEXT NOT NULL DEFAULT 'IN_APP', delivery_status TEXT NOT NULL DEFAULT 'PENDING', delivered_at TIMESTAMPTZ(3), failure_reason TEXT, dedupe_key TEXT NOT NULL UNIQUE, read_at TIMESTAMPTZ(3));
CREATE INDEX notification_events_read_at_created_at_idx ON notification_events(read_at,created_at);
CREATE INDEX notification_events_watchlist_id_idx ON notification_events(watchlist_id);
CREATE TABLE digest_settings (id TEXT PRIMARY KEY DEFAULT 'workspace', digest_enabled BOOLEAN NOT NULL DEFAULT true, digest_time TEXT NOT NULL DEFAULT '08:00', timezone TEXT NOT NULL DEFAULT 'Asia/Shanghai');
CREATE TABLE daily_digests (id TEXT PRIMARY KEY, digest_date TEXT NOT NULL UNIQUE, timezone TEXT NOT NULL, window_start TIMESTAMPTZ(3) NOT NULL, window_end TIMESTAMPTZ(3) NOT NULL, generated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, summary JSONB NOT NULL);
CREATE TABLE source_health_checkpoints (source_id TEXT PRIMARY KEY, status TEXT NOT NULL, revision INTEGER NOT NULL DEFAULT 0);
